web:
    build:
        .
    volumes:
        - ".:/var/localshop"
    environment:
        - DJANGO_SECRET_KEY=a7d03faa0c054b3dba38b396bf3c7996
        - DATABASE_URL=postgres://localshop:shopping@db/localshop
        - DJANGO_MEDIA_ROOT=/var/localshop/media
    links:
        - db
    ports:
        - "8000:8000"
    command: uwsgi --http 0.0.0.0:8000 --module localshop.wsgi --master --die-on-term


worker:
    build:
        .
    volumes:
        - ".:/var/localshop"
    environment:
        - DJANGO_SECRET_KEY=a7d03faa0c054b3dba38b396bf3c7996
        - DATABASE_URL=postgres://localshop:shopping@db/localshop
        - DJANGO_MEDIA_ROOT=/var/localshop/media
    links:
        - db
    entrypoint:
        localshop
    command: 
        localshop celery worker -B -E


db:
    image: sameersbn/postgresql:9.4
    environment:
        - DB_NAME=localshop
        - DB_USER=localshop
        - DB_PASS=shopping
    ports:
        - "5432"
